name: EPG IT

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  

permissions:
  contents: write

concurrency:
  group: epg-daily
  cancel-in-progress: true

jobs:
  build-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Generate docs/epg-it.xml
        run: |
          mkdir -p docs
          node ./scripts/build-epg.js > docs/epg-it.xml

      - name: Create log file
        run: |
          # Scrive solo l'ora di Londra (es: 14:30) nel file log
          TZ="Europe/London" date +"%H:%M" > log

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Aggiunge il file EPG e il file log con l'orario
          git add docs/epg.xml log

          # Verifica se ci sono cambiamenti effettivi
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "github-actions[bot]"
          git push
